# Generated by Django 6.0.1 on 2026-02-03 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('major', models.CharField(max_length=250)),
                ('grade', models.FloatField()),
                ('grade_margin', models.FloatField()),
                ('passing_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Academic',
                'verbose_name_plural': 'Academics',
                'db_table': 'academics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(upload_to='teacher_attachments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('teaching_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Extra Information',
                'verbose_name_plural': 'Extra Information',
                'db_table': 'extrainformation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.CharField(max_length=150)),
                ('from_time', models.DateField(blank=True, null=True)),
                ('to_time', models.DateField(blank=True, null=True)),
                ('current_working', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
                'db_table': 'professional_experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('notes', models.TextField(help_text='Describe what you teach in shortly such topics so that student can understand')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='subject.subject')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'ordering': ['name'],
            },
        ),
    ]
