# Generated by Django 6.0.1 on 2026-03-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='cartificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher-certificates'),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
