# Generated by Django 6.0.1 on 2026-03-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_academic_cartificate_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='passing_year',
            field=models.IntegerField(),
        ),
    ]
