# Generated by Django 6.0.1 on 2026-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_academic_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='cartificate',
            field=models.FileField(null=True, upload_to='teacher-certificates'),
        ),
    ]
