# Generated by Django 6.0.1 on 2026-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_academic_cartificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='cartificate',
            field=models.FileField(upload_to='teacher-certificates'),
        ),
    ]
