# Generated by Django 6.0.1 on 2026-03-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_academic_cartificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='cartificate',
        ),
    ]
