# Generated by Django 6.0.1 on 2026-03-05 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_remove_academic_cartificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionalexperience',
            options={'verbose_name': 'Professional Experience', 'verbose_name_plural': 'Professional Experiences'},
        ),
        migrations.AddField(
            model_name='batch',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='class_link',
            field=models.URLField(default='https://www.facebook.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
    ]
